#!/bin/zsh

cat config.txt >> ~/.zshrc

source ~/.zshrc

cp ~/Downloads/gindle-master/gindle ~/custom_tools/

cp ~/Downloads/gindle-master/link_finder.py ~/custom_tools/

echo "The gindle is ready to rock"
